import assert from 'assert';
import { validateOp } from '../../server/optypes';
const ok = (p: any) => validateOp('agent_config_set', p) === null;
assert(ok({ set: { pg_data: '/data/pg', pg_port: 5433 } }));
assert(ok({ set: { pg_data: null } }), 'null resets an override');
assert(!ok({}) && !ok({ set: {} }) && !ok({ set: [] }) && !ok({ set: 'x' }));
assert(!ok({ set: { auth_token: 'x' } }), 'only whitelisted settings');
assert(!ok({ set: { repo_path: { a: 1 } } }) && !ok({ set: { repo_path: '/a\nb' } }));
assert.strictEqual(validateOp('agent_config_get', {}), null);
assert(validateOp('pg_set_param', { name: 'archive_command', value: 'x' }) !== null && validateOp('pg_set_param', { name: 'shared_preload_libraries', value: 'x' }) !== null);
assert.strictEqual(validateOp('pg_set_param', { name: 'work_mem', value: '64MB' }), null);
assert(validateOp('patroni_config_patch', { patch: { postgresql: { parameters: { archive_command: 'rm -rf /' } } } }) !== null);
assert(validateOp('patroni_config_patch', { patch: { postgresql: { authentication: {} } } }) !== null && validateOp('patroni_config_patch', { patch: { restapi: {} } }) !== null);
assert.strictEqual(validateOp('patroni_config_patch', { patch: { ttl: 30, postgresql: { parameters: { max_connections: 200 } } } }), null);
console.log('agent config op tests OK');
