/**
 * Self-announcement of new servers ("join requests").
 *
 * An agent installed WITHOUT an enrollment token announces itself here; nothing is trusted until an administrator approves it in the web UI.
 *   agent  --POST /api/agent/request-join {fingerprint, secret_hash, node_name, discovery}-->  pending request (no credentials exist yet)
 *   admin  --POST /api/join-requests/:id/approve-->  node is created with token hash = the agent's own secret_hash
 *   agent  --POST /api/agent/join-status {fingerprint, secret}-->  { approved, node_id, cluster_id }  and keeps using its own secret as bearer token
 * The secret is generated by the agent and never travels to the console (only its hash), so approval hands out nothing that could be intercepted.
 * Abuse limits: the endpoint is unauthenticated, so it is capped (pending total, per source address, field sizes) and can be switched off in Settings.
 */
import crypto from 'crypto';
import { Store, NodeRecord, sha256, newId, nowIso } from './store';
import * as ops from './ops';
import { refreshCluster } from './agents';
import { advanced } from './approvals';

const MAX_PENDING = 100, MAX_PER_IP = 10;
const PENDING_TTL_MS = 48 * 3600_000, REJECTED_TTL_MS = 24 * 3600_000, DONE_TTL_MS = 24 * 3600_000;
const FP = /^[A-Za-z0-9_-]{16,64}$/, HASH = /^[0-9a-f]{64}$/, NAME = /^[A-Za-z0-9_.-]{1,63}$/;
const safeEq = (a: any, b: any) => typeof a === 'string' && typeof b === 'string' && a.length === b.length && crypto.timingSafeEqual(Buffer.from(a), Buffer.from(b));
const trunc = (v: any, n = 120) => String(v ?? '').slice(0, n);

export const joinEnabled = (st: any) => advanced(st).joinRequests !== false;

/** What the console keeps from the unauthenticated discovery report: a few short strings, never the whole payload. */
export function summarize(disc: any) {
  const inst = ((disc?.postgres_instances || []) as any[]).slice(0, 5).map(i => ({ version: trunc(i.version, 20), data_directory: trunc(i.data_directory, 200), port: Number(i.port) || undefined, cluster_key: trunc(i.cluster_key, 120) || undefined, patroni_scope: trunc(i.patroni?.scope, 80) || undefined, role: trunc(i.role, 20) || undefined }));
  const pat = ((disc?.patroni_clusters || []) as any[])[0]?.scope;
  const procs = [...new Set(((disc?.running_processes || []) as any[]).map(p => trunc(p?.name, 20)).filter(Boolean))].slice(0, 12);
  const warns = ((disc?.warnings || []) as any[]).slice(0, 4).map(w => trunc(w, 200));
  const diag = { procs, warnings: warns, uid: Number.isInteger(disc?.run_as?.uid) ? disc.run_as.uid : undefined, scan_ms: Number(disc?.scan_duration_ms) || undefined };
  return { diag, hostname: trunc(disc?.host?.hostname || disc?.hostname, 80), os: trunc(disc?.host?.os || disc?.os, 80), postgres: inst, patroni_scope: trunc(pat || inst[0]?.patroni_scope, 80) || undefined };
}

function prune(list: any[], now: number) {
  return list.filter(r => r.status === 'pending' ? now - Date.parse(r.lastSeenAt) < PENDING_TTL_MS : r.status === 'rejected' ? now - Date.parse(r.decidedAt) < REJECTED_TTL_MS : now - Date.parse(r.decidedAt) < DONE_TTL_MS);
}

export function mountJoinRoutes(app: any, store: Store) {
  const ipOf = (req: any) => String(req.socket?.remoteAddress || '').slice(0, 64);

  app.post('/api/agent/request-join', async (req: any, res: any) => {
    const b = req.body || {};
    if (!joinEnabled(store.peek())) return res.status(403).json({ error: 'join_disabled', message: 'L’annuncio automatico dei server è disattivato: usa un token di iscrizione.' });
    if (!FP.test(String(b.fingerprint || '')) || !HASH.test(String(b.secret_hash || '')) || !NAME.test(String(b.node_name || ''))) return res.status(400).json({ error: 'invalid_request' });
    const ip = ipOf(req); const now = Date.now();
    const out = await store.mutate(d => {
      const list = (d.settings.joinRequests = prune(d.settings.joinRequests || [], now));
      const cur = list.find((r: any) => r.fingerprint === b.fingerprint);
      if (cur) {
        if (!safeEq(cur.secretHash, b.secret_hash)) return { code: 409, body: { error: 'fingerprint_conflict' } };
        cur.lastSeenAt = nowIso(); cur.ip = ip;
        if (cur.status === 'pending') { cur.summary = summarize(b.discovery); cur.agentVersion = trunc(b.agent_version, 30); }
        return { code: 200, body: { status: cur.status } };
      }
      const pend = list.filter((r: any) => r.status === 'pending');
      if (pend.length >= MAX_PENDING || pend.filter((r: any) => r.ip === ip).length >= MAX_PER_IP) return { code: 429, body: { error: 'too_many_requests', message: 'Troppe richieste in attesa.' } };
      list.push({ id: newId('join'), fingerprint: b.fingerprint, secretHash: b.secret_hash, nodeName: b.node_name, ip, status: 'pending', createdAt: nowIso(), lastSeenAt: nowIso(),
        agentVersion: trunc(b.agent_version, 30), summary: summarize(b.discovery) });
      return { code: 201, body: { status: 'pending' } };
    });
    res.status(out.code).json(out.body);
  });

  app.post('/api/agent/join-status', async (req: any, res: any) => {
    const b = req.body || {};
    const r = (store.peek().settings.joinRequests || []).find((x: any) => x.fingerprint === String(b.fingerprint || ''));
    if (!r || !safeEq(r.secretHash, sha256(String(b.secret || '')))) return res.status(404).json({ error: 'unknown_request' });
    if (r.status === 'approved') return res.json({ status: 'approved', node_id: r.nodeId, cluster_id: r.clusterId, heartbeat_interval: 10 });
    res.json({ status: r.status });
  });

  // ---- operator side (admin only: the list shows source addresses and host details) ----------------------
  const view = () => {
    const st = store.peek(); const now = Date.now();
    return (st.settings.joinRequests || []).filter((r: any) => r.status === 'pending' && now - Date.parse(r.lastSeenAt) < PENDING_TTL_MS).map((r: any) => {
      const key = r.summary?.postgres?.find((i: any) => i.cluster_key)?.cluster_key;
      const match = key ? (st.clusters as any[]).find(c => c.clusterKey === key) : undefined;
      const known = Object.values(st.nodes).some((n: any) => n.name === r.nodeName);
      return { id: r.id, nodeName: r.nodeName, ip: r.ip, createdAt: r.createdAt, lastSeenAt: r.lastSeenAt, agentVersion: r.agentVersion, summary: r.summary, matchCluster: match ? { id: match.id, name: match.name, environment: match.environment } : null, nameInUse: known };
    });
  };
  app.get('/api/join-requests', (_req: any, res: any) => res.json({ requests: view(), enabled: joinEnabled(store.peek()) }));

  app.post('/api/join-requests/:id/approve', async (req: any, res: any) => {
    const b = req.body || {}; const actor = req.actor || 'admin';
    const out = await store.mutate(d => {
      const r = (d.settings.joinRequests || []).find((x: any) => x.id === req.params.id);
      if (!r) return { code: 404, body: { error: 'not_found' } };
      if (r.status !== 'pending') return { code: 409, body: { error: 'not_pending', message: 'Richiesta già gestita.' } };
      if (Object.values(d.nodes).some((n: any) => n.name === r.nodeName)) return { code: 409, body: { error: 'name_in_use', message: `Esiste già un server chiamato ${r.nodeName}.` } };
      const key = r.summary?.postgres?.find((i: any) => i.cluster_key)?.cluster_key as string | undefined;
      let cluster: any = b.clusterId ? d.clusters.find((c: any) => c.id === b.clusterId && !c.isSandbox) : (key ? d.clusters.find((c: any) => c.clusterKey === key) : undefined);
      if (b.clusterId && !cluster) return { code: 404, body: { error: 'cluster_not_found' } };
      if (!cluster) {
        const env = ['prod', 'prep', 'int', 'dev', 'test'].includes(b.environment) ? b.environment : null;
        if (!env) return { code: 400, body: { error: 'environment_required', message: 'Scegli l’ambiente del nuovo cluster.' } };
        const name = trunc(b.name, 60).trim() || r.summary?.patroni_scope || `pg-${r.nodeName}`;
        cluster = { id: newId('cl'), name, environment: env, clusterKey: key, source: 'agent', isSandbox: false, status: 'degraded', databases: [], hbaRules: [], features: {}, createdAt: nowIso() };
        d.clusters.push(cluster);
      }
      const id = newId('node');
      d.nodes[id] = { id, name: r.nodeName, tokenHash: r.secretHash, enrolledAt: nowIso(), clusterId: cluster.id, clusterKey: key, agentVersion: r.agentVersion, remoteIp: r.ip, lastSeen: undefined } as NodeRecord;
      r.status = 'approved'; r.nodeId = id; r.clusterId = cluster.id; r.decidedAt = nowIso(); r.decidedBy = actor;
      ops.audit(d, { clusterId: cluster.id, actor, action: 'agent.join.approve', status: 'OK', details: { node: r.nodeName, ip: r.ip, newCluster: !b.clusterId && !key } });
      refreshCluster(d, cluster.id);
      return { code: 200, body: { ok: true, nodeId: id, clusterId: cluster.id } };
    });
    res.status(out.code).json(out.body);
  });

  app.post('/api/join-requests/:id/reject', async (req: any, res: any) => {
    const actor = req.actor || 'admin';
    const out = await store.mutate(d => {
      const r = (d.settings.joinRequests || []).find((x: any) => x.id === req.params.id);
      if (!r) return 404 as const; if (r.status !== 'pending') return 409 as const;
      r.status = 'rejected'; r.decidedAt = nowIso(); r.decidedBy = actor;
      ops.audit(d, { actor, action: 'agent.join.reject', status: 'OK', details: { node: r.nodeName, ip: r.ip } });
      return 200 as const;
    });
    res.status(out).json(out === 200 ? { ok: true } : { error: out === 404 ? 'not_found' : 'not_pending' });
  });
}
